apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-api-deployment
spec:
  template:
    metadata:
      labels:
        name: greeting-api-pod
        type: backend
    spec:
      containers:
        - name: greeing-api
          image: patilashwin/greeting-api:1.0
          ports:
            - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      name: greeting-api-pod
      type: backend
  

